name: app_covid_samir
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  http: ^0.13.1
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  
  uses-material-design: true
  assets:
    - assets/logo/MaskGroup215.png
    - assets/logo/MaskGroup216.png
    - assets/images/SmallArrowFw.png
    - assets/images/Asia.png
    - assets/images/Africa.png
    - assets/images/Australia/Oceania.png
    - assets/images/Europe.png
    - assets/images/North America.png
    - assets/images/South America.png


  fonts:
    - family: Ubuntu-Bold
      fonts:
        - asset: assets/fonts/Ubuntu-Bold.ttf

    - family: Ubuntu-Medium
      fonts:
        - asset: assets/fonts/Ubuntu-Medium.ttf
    
    - family: Ubuntu-Regular
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
      
        

